import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/index.module.scss";
import Banner from "@/components/Banner";
import WhatIDO from "@/components/WhatIDO";
import Projects from "@/components/Projects";
import About from "@/components/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <About />
      <WhatIDO />
      <Projects />
    </>
  );
}
